#!/bin/sh
# ======================
# GemOS rcS - sysinit script
# ======================

# --- Basic File System ---
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /tmp

# --- Basic Environment ---
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export HOME=/root
export TERM=linux
hostname gemos

# --- Load Extensions ---
if [ -d /etc/gemos/init.d ]; then
    for f in /etc/gemos/init.d/*; do
        [ -f "$f" ] && sh "$f"
    done
fi

echo ""
echo "Welcome to GemOS"
echo ""